# Generated by Django 3.1.3 on 2020-12-11 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sport',
            old_name='game_id',
            new_name='game',
        ),
    ]
