# Generated by Django 3.1.4 on 2020-12-11 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4)),
                ('region', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=255)),
            ],
        ),
    ]
