# Generated by Django 3.1.4 on 2020-12-11 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noc',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
