# Generated by Django 3.1.4 on 2020-12-11 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('noc', '0002_auto_20201211_0345'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=2)),
                ('team', models.CharField(max_length=100)),
                ('noc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noc.noc')),
            ],
        ),
        migrations.CreateModel(
            name='Athlete_instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medal', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('height', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=100)),
                ('athlete_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athletes.athlete')),
                ('event_id', models.ManyToManyField(to='events.Event')),
            ],
        ),
    ]
