# Generated by Django 3.1.3 on 2020-12-11 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20201211_1811'),
        ('athletes', '0002_auto_20201211_1811'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Athlete_instance',
            new_name='AthleteInstance',
        ),
    ]
